<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\PixelGameStudio.Core\PixelGameStudio.Core.csproj" />
    <ProjectReference Include="..\PixelGameStudio.Domain\PixelGameStudio.Domain.csproj" />
    <ProjectReference Include="..\PixelGameStudio.Rendering\PixelGameStudio.Rendering.csproj" />
    <ProjectReference Include="..\PixelGameStudio.Assets\PixelGameStudio.Assets.csproj" />
  </ItemGroup>
</Project>
